package it.polimi.ingsw.GUI;

import it.polimi.ingsw.model.God;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import java.net.URL;
import java.util.List;
import java.util.ResourceBundle;

/**
 * It is the window where the player can choose the god to play with, among those chosen by the challenger.
 */
public class ChooseGodWindow extends GameWindow implements Initializable {

    /**
     * It is the button to scroll backwards the gods
     */
    @FXML
    public Button backGodButton;

    /**
     * It is the button to scroll forward the gods
     */
    @FXML
    public Button nextGodButton;

    /**
     * It shows god's name.
     * It changes when the current god on screen changes.
     */
    @FXML
    public Label godLabel;

    /**
     * It shows a short description of god's power.
     */
    @FXML
    public Label powerLabel;

    /**
     * It is the button to press to choose a god.
     */
    @FXML
    public Button chooseButton;

    /**
     * It is the image where the current god is shown. It changes by pressing nextGodButton and backGodButton.
     */
    @FXML
    public ImageView godCard;

    /**
     * It is the image of chooseButton.
     */
    @FXML
    public ImageView chooseButtonImage;

    /**
     * It is the image of backGodButton.
     */
    @FXML
    public ImageView backButtonImage;

    /**
     * It is the image of nextGodButton.
     */
    @FXML
    public ImageView nextButtonImage;

    /**
     * It is the pane of this window.
     */
    @FXML
    public AnchorPane chooseGodPane;

    /**
     * It is the stage which succeeds the current one.
     */
    private final Stage nextStage = new Stage();

    /**
     * It is the god shown on mirror.
     */
    private God currGod = guiHandler.getGods().get(0);

    /**
     * It changes the current god, rolling currGod back and loading a new image on godCard.
     * @param actionEvent generated by clicking on backGodButton.
     */
    public void backGod(ActionEvent actionEvent) {
        if (currGod == guiHandler.getGods().get(0)){
            if (guiHandler.getNumOfPlayers() == 3 && guiHandler.getGods().size() == 3) currGod = guiHandler.getGods().get(2);
            else currGod = guiHandler.getGods().get(1);
        } else if (currGod == guiHandler.getGods().get(1)){
            currGod = guiHandler.getGods().get(0);
        } else if (currGod == guiHandler.getGods().get(2)){
            currGod = guiHandler.getGods().get(1);
        }
        setGodImage();
    }

    /**
     * It changes the current god, rolling currGod on and loading a new image on godCard.
     * @param actionEvent generated by clicking on nextGodButton.
     */
    public void nextGod(ActionEvent actionEvent) {
        if (currGod == guiHandler.getGods().get(0)){
            currGod = guiHandler.getGods().get(1);
        } else if (currGod == guiHandler.getGods().get(1)){
            if (guiHandler.getNumOfPlayers() == 3 && guiHandler.getGods().size() == 3) currGod = guiHandler.getGods().get(2);
            else currGod = guiHandler.getGods().get(0);
        } else if (currGod == guiHandler.getGods().get(2)){
            currGod = guiHandler.getGods().get(0);
        }
        setGodImage();
    }

    /**
     * It loads the image of the current god on screen.
     */
    private void setGodImage() {
        switch (currGod){
            case APOLLO:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0043_god_and_hero_cards_0013_apollo.png"));
                break;
            }
            case ARTEMIS:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0054_god_and_hero_cards_0002_Artemis.png"));
                break;
            }
            //
            case ATHENA:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0052_god_and_hero_cards_0004_Athena.png"));
                break;
            }
            case ATLAS:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0053_god_and_hero_cards_0003_Atlas.png"));
                break;
            }
            //
            case CHARON:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0020_god_and_hero_cards_0036_charon.png"));
                break;
            }
            //
            case DEMETER:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0050_god_and_hero_cards_0006_Demeter.png"));
                break;
            }
            case HEPHAESTUS:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0009_god_and_hero_cards_0047_Hephaestus.png"));
                break;
            }
            //
            case HYPNUS:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0019_god_and_hero_cards_0037_Hypnus.png"));
                break;
            }
            case MINOTAUR:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0008_god_and_hero_cards_0048_Minotaur.png"));
                break;
            }
            case MORTAL:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0000_god_and_hero_cards_0057_HumanGord.png"));
                break;
            }
            case PAN:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0046_god_and_hero_cards_0010_Pan.png"));
                break;
            }
            case POSEIDON:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0045_god_and_hero_cards_0011_Poseidon.png"));
                break;
            }
            case PROMETHEUS:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0004_god_and_hero_cards_0052_Prometheus.png"));
                break;
            }
            case TRITON:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0028_god_and_hero_cards_0028_triton.png"));
                break;
            }
            case ZEUS:{
                godCard.setImage(new Image("FullGodAvatar/full_0000s_0014_god_and_hero_cards_0042_zeus.png"));
                break;
            }
        }
        godLabel.setText(currGod.toString());
        powerLabel.setText(currGod.getPower());
    }

    /**
     * It let the player to choose his/her god. It changes the current stage.
     * @param actionEvent
     */
    public void chooseGod(ActionEvent actionEvent) {
        guiHandler.setClientMessage(currGod);
        guiHandler.loadFXMLFile(chooseButton,nextStage,"/GUIScenes/beginningMatchWindow.fxml");
    }

    /**
     * It shows a graphical effect when pressing backGodButton.
     * @param mouseEvent generated by pressing backGodButton.
     */
    public void clickBack(MouseEvent mouseEvent) {
        backButtonImage.setImage(new Image("Buttons/btn_back_pressed.png"));
    }

    /**
     * It shows a graphical effect when releasing backGodButton.
     * @param mouseEvent generated by releasing backGodButton.
     */
    public void releaseBack(MouseEvent mouseEvent) {
        backButtonImage.setImage(new Image("Buttons/btn_back.png"));
    }

    /**
     * It shows a graphical effect when pressing nextGodButton.
     * @param mouseEvent generated by pressing nextGodButton.
     */
    public void clickNext(MouseEvent mouseEvent) {
        nextButtonImage.setImage(new Image("Buttons/btn_back_pressed.png"));
    }

    /**
     * It shows a graphical effect when releasing nextGodButton.
     * @param mouseEvent generated by releasing nextGodButton.
     */
    public void releaseNext(MouseEvent mouseEvent) {
        nextButtonImage.setImage(new Image("Buttons/btn_back.png"));
    }

    /**
     * It shows a graphical effect when pressing chooseButton.
     * @param mouseEvent generated by pressing chooseButton.
     */
    public void clickChoose(MouseEvent mouseEvent) {
        chooseButtonImage.setImage(new Image("Buttons/cm_btn_blue_pressed.png"));
    }

    /**
     * It shows a graphical effect when releasing chooseButton.
     * @param mouseEvent generated by releasing chooseButton.
     */
    public void releaseChoose(MouseEvent mouseEvent) {
        chooseButtonImage.setImage(new Image("Buttons/cm_btn_blue.png"));
    }

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        currGod = guiHandler.getGods().get(0);
        setGodImage();
        guiHandler.setCurrPane(chooseGodPane);
    }
}
