package it.polimi.ingsw.GUI;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.stage.Stage;

/**
 * It is the window where the player can choose the way she/he wants to start a game.
 */
public class ModeWindow extends GameWindow  {

    /**
     * If pressed, the players is choosing the mode NEW_GAME.
     */
    @FXML
    public Button newGameButton;

    /**
     * If pressed, the players is choosing the mode EXISTING_MATCH.
     */
    @FXML
    public Button friendsButton;

    /**
     * If pressed, the players is choosing the mode RANDOM_GAME.
     */
    @FXML
    public Button randomGameButton;

    /**
     * It is the stage which succeeds the current one.
     */
    private final Stage nextStage = new Stage();

    /**
     * It sets the mode to NEW_GAME and load a new stage
     * @param actionEvent generated by newGameButton.
     */
    public void newGame(ActionEvent actionEvent) {
        guiHandler.setMode(Mode.NEW_GAME);
        guiHandler.loadFXMLFile(newGameButton,nextStage,"/GUIScenes/newGameWindow.fxml");

    }

    /**
     * It sets the mode to EXISTING_MATCH and load a new stage.
     * @param actionEvent generated by friendsButton.
     */
    public void playWithFriends(ActionEvent actionEvent) {
        guiHandler.setMode(Mode.EXISTING_MATCH);
        guiHandler.loadFXMLFile(newGameButton,nextStage,"/GUIScenes/existingGameWindow.fxml");
    }

    /**
     * It sets the mode to RANDOM_GAME and load a new stage.
     * @param actionEvent generated by randomGameButton.
     */
    public void randomGame(ActionEvent actionEvent) {
        guiHandler.setMode(Mode.RANDOM_MATCH);
        guiHandler.loadFXMLFile(newGameButton,nextStage,"/GUIScenes/newGameWindow.fxml");
    }
}
