package it.polimi.ingsw.GUI;

import javafx.concurrent.Task;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.RadioButton;
import javafx.scene.control.ToggleGroup;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

/**
 * It is the window where the player chooses the number of players.
 */

public class NewGameWindow extends GameWindow {

    /**
     * If pressed, it sets the number of player at 2.
     */
    @FXML
    public RadioButton twoPlayersButton;

    /**
     * If pressed, it sets the number of player at 3.
     */
    @FXML
    public RadioButton threePlayersButton;

    /**
     * It let the stage change, if one of the radioButton is chosen.
     */
    @FXML
    public Button nextButton;

    /**
     * It is the stage that succeeds the current one.
     */
    @FXML
    private final Stage nextStage = new Stage();

    /**
     * It unchecks threePlayersButton.
     * @param actionEvent generated by twoPlayersButton.
     */
    public void uncheckThreePlayersButton(ActionEvent actionEvent) {
        threePlayersButton.setSelected(false);
        guiHandler.setNumOfPlayers(2);
    }

    /**
     * It unchecks twoPlayersButton.
     * @param actionEvent generated by threePlayersButton.
     */
    public void uncheckTwoPlayersButton(ActionEvent actionEvent) {
        twoPlayersButton.setSelected(false);
        guiHandler.setNumOfPlayers(3);
    }

    /**
     * It changes the stage.
     * @param actionEvent generated by nextButton.
     */
    public void goFurther(ActionEvent actionEvent) {

        if (twoPlayersButton.isSelected() || threePlayersButton.isSelected()){
            guiHandler.loadFXMLFile(nextButton, nextStage, "/GUIScenes/waitingWindow.fxml");
        }
    }
}
