package it.polimi.ingsw.GUI;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import java.io.IOException;

/**
 * It is the window where the player can choose a nickname.
 */

public  class NicknameWindow extends GameWindow {

    /**
     * It is the field to fill in with the chosen nickame.
     */
    @FXML
    public TextField fieldNickname;

    /**
     * It advises on screen if the nickname is accepted or not.
     */
    @FXML
    public Label adviseLabel;

    /**
     * It is the button bound to the method goFurther. It lets the stage and the scene change, if clicked.
     */
    @FXML
    private Button nextButton;

    /**
     * It is the nickname chosen by the player.
     */
    private String nickname;

    /**
     * It is the stage which succeeds the current one.
     */
    private final Stage nextStage = new Stage();

    /**
     * It establish if the nickname has been accepted by the server.
     */
    private boolean nicknameAccepted = false;


    /**
     * It sends the nickname to the server.
     * If this is accepted, the stage changes. Else, the player is asked to choose another nickname.
     * @param actionEvent It is generated by clicking on nextButton or by pressing Enter.
     */
    @FXML
    public void goFurther(ActionEvent actionEvent) {

        nickname = fieldNickname.getText().toUpperCase();
        nicknameAccepted = guiHandler.askNameAvailability(nickname);
        if (nicknameAccepted) {
            guiHandler.loadFXMLFile(nextButton,nextStage,"/GUIScenes/modeWindow.fxml");
        }
        else {
            fieldNickname.clear();
            adviseLabel.setText("Please retype a valid nickname");
        }
    }
}
